package com.cluser.dao.model;

public class TOrgTreePath extends TOrgTreePathKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_tree_path.depth
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private Short depth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_tree_path.depth
     *
     * @return the value of t_org_tree_path.depth
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public Short getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_tree_path.depth
     *
     * @param depth the value for t_org_tree_path.depth
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setDepth(Short depth) {
        this.depth = depth;
    }
}