package com.cluser.dao.model;

import java.util.Date;

public class TOrganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.id
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.name
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.description
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.address
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.email
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.type
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.status
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.more_info
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private String moreInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.created_time
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.updated_time
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.id
     *
     * @return the value of t_organization.id
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.id
     *
     * @param id the value for t_organization.id
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.name
     *
     * @return the value of t_organization.name
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.name
     *
     * @param name the value for t_organization.name
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.description
     *
     * @return the value of t_organization.description
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.description
     *
     * @param description the value for t_organization.description
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.address
     *
     * @return the value of t_organization.address
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.address
     *
     * @param address the value for t_organization.address
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.email
     *
     * @return the value of t_organization.email
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.email
     *
     * @param email the value for t_organization.email
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.type
     *
     * @return the value of t_organization.type
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.type
     *
     * @param type the value for t_organization.type
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.status
     *
     * @return the value of t_organization.status
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.status
     *
     * @param status the value for t_organization.status
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.more_info
     *
     * @return the value of t_organization.more_info
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public String getMoreInfo() {
        return moreInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.more_info
     *
     * @param moreInfo the value for t_organization.more_info
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setMoreInfo(String moreInfo) {
        this.moreInfo = moreInfo == null ? null : moreInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.created_time
     *
     * @return the value of t_organization.created_time
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.created_time
     *
     * @param createdTime the value for t_organization.created_time
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.updated_time
     *
     * @return the value of t_organization.updated_time
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.updated_time
     *
     * @param updatedTime the value for t_organization.updated_time
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}