package com.cluser.dao.model;

public class TUserSchema {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.id
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.basic_attribute
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private boolean basicAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.display_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.domain_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String domainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.column_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.data_type
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.mandatory
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private boolean mandatory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.searchable
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private boolean searchable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.maint_level
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String maintLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.constraint_rule
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String constraintRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_schema.description
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.id
     *
     * @return the value of t_user_schema.id
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.id
     *
     * @param id the value for t_user_schema.id
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.basic_attribute
     *
     * @return the value of t_user_schema.basic_attribute
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public boolean isBasicAttribute() {
        return basicAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.basic_attribute
     *
     * @param basicAttribute the value for t_user_schema.basic_attribute
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setBasicAttribute(boolean basicAttribute) {
        this.basicAttribute = basicAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.display_name
     *
     * @return the value of t_user_schema.display_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.display_name
     *
     * @param displayName the value for t_user_schema.display_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.domain_name
     *
     * @return the value of t_user_schema.domain_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.domain_name
     *
     * @param domainName the value for t_user_schema.domain_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName == null ? null : domainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.column_name
     *
     * @return the value of t_user_schema.column_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.column_name
     *
     * @param columnName the value for t_user_schema.column_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.data_type
     *
     * @return the value of t_user_schema.data_type
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.data_type
     *
     * @param dataType the value for t_user_schema.data_type
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.mandatory
     *
     * @return the value of t_user_schema.mandatory
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public boolean isMandatory() {
        return mandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.mandatory
     *
     * @param mandatory the value for t_user_schema.mandatory
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setMandatory(boolean mandatory) {
        this.mandatory = mandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.searchable
     *
     * @return the value of t_user_schema.searchable
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public boolean isSearchable() {
        return searchable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.searchable
     *
     * @param searchable the value for t_user_schema.searchable
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setSearchable(boolean searchable) {
        this.searchable = searchable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.maint_level
     *
     * @return the value of t_user_schema.maint_level
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getMaintLevel() {
        return maintLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.maint_level
     *
     * @param maintLevel the value for t_user_schema.maint_level
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setMaintLevel(String maintLevel) {
        this.maintLevel = maintLevel == null ? null : maintLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.constraint_rule
     *
     * @return the value of t_user_schema.constraint_rule
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getConstraintRule() {
        return constraintRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.constraint_rule
     *
     * @param constraintRule the value for t_user_schema.constraint_rule
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setConstraintRule(String constraintRule) {
        this.constraintRule = constraintRule == null ? null : constraintRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_schema.description
     *
     * @return the value of t_user_schema.description
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_schema.description
     *
     * @param description the value for t_user_schema.description
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}