package com.cluser.dao.model;

import java.util.Date;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.full_name
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.preferred_username
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String preferredUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.nickname
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birthdate
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password_meta_info
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String passwordMetaInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password_status
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String passwordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.gender
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.picture
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.website
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.salt
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email_verified
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private Boolean emailVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone_number
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone_number_verified
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private Boolean phoneNumberVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.zoneinfo
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String zoneinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.profile
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.locale
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String locale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.type
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.address
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.created_by
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_login
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.created_time
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.updated_time
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.full_name
     *
     * @return the value of t_user.full_name
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.full_name
     *
     * @param fullName the value for t_user.full_name
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.preferred_username
     *
     * @return the value of t_user.preferred_username
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getPreferredUsername() {
        return preferredUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.preferred_username
     *
     * @param preferredUsername the value for t_user.preferred_username
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setPreferredUsername(String preferredUsername) {
        this.preferredUsername = preferredUsername == null ? null : preferredUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.nickname
     *
     * @return the value of t_user.nickname
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.nickname
     *
     * @param nickname the value for t_user.nickname
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.birthdate
     *
     * @return the value of t_user.birthdate
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.birthdate
     *
     * @param birthdate the value for t_user.birthdate
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password_meta_info
     *
     * @return the value of t_user.password_meta_info
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getPasswordMetaInfo() {
        return passwordMetaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password_meta_info
     *
     * @param passwordMetaInfo the value for t_user.password_meta_info
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setPasswordMetaInfo(String passwordMetaInfo) {
        this.passwordMetaInfo = passwordMetaInfo == null ? null : passwordMetaInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password_status
     *
     * @return the value of t_user.password_status
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getPasswordStatus() {
        return passwordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password_status
     *
     * @param passwordStatus the value for t_user.password_status
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setPasswordStatus(String passwordStatus) {
        this.passwordStatus = passwordStatus == null ? null : passwordStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.gender
     *
     * @return the value of t_user.gender
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.gender
     *
     * @param gender the value for t_user.gender
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.picture
     *
     * @return the value of t_user.picture
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.picture
     *
     * @param picture the value for t_user.picture
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.website
     *
     * @return the value of t_user.website
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.website
     *
     * @param website the value for t_user.website
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.salt
     *
     * @return the value of t_user.salt
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.salt
     *
     * @param salt the value for t_user.salt
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email_verified
     *
     * @return the value of t_user.email_verified
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public Boolean getEmailVerified() {
        return emailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email_verified
     *
     * @param emailVerified the value for t_user.email_verified
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setEmailVerified(Boolean emailVerified) {
        this.emailVerified = emailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone_number
     *
     * @return the value of t_user.phone_number
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone_number
     *
     * @param phoneNumber the value for t_user.phone_number
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone_number_verified
     *
     * @return the value of t_user.phone_number_verified
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public Boolean getPhoneNumberVerified() {
        return phoneNumberVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone_number_verified
     *
     * @param phoneNumberVerified the value for t_user.phone_number_verified
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setPhoneNumberVerified(Boolean phoneNumberVerified) {
        this.phoneNumberVerified = phoneNumberVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.zoneinfo
     *
     * @return the value of t_user.zoneinfo
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getZoneinfo() {
        return zoneinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.zoneinfo
     *
     * @param zoneinfo the value for t_user.zoneinfo
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setZoneinfo(String zoneinfo) {
        this.zoneinfo = zoneinfo == null ? null : zoneinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.profile
     *
     * @return the value of t_user.profile
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.profile
     *
     * @param profile the value for t_user.profile
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setProfile(String profile) {
        this.profile = profile == null ? null : profile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.locale
     *
     * @return the value of t_user.locale
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getLocale() {
        return locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.locale
     *
     * @param locale the value for t_user.locale
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setLocale(String locale) {
        this.locale = locale == null ? null : locale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.type
     *
     * @return the value of t_user.type
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.type
     *
     * @param type the value for t_user.type
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.address
     *
     * @return the value of t_user.address
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.address
     *
     * @param address the value for t_user.address
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.created_by
     *
     * @return the value of t_user.created_by
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.created_by
     *
     * @param createdBy the value for t_user.created_by
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_login
     *
     * @return the value of t_user.last_login
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_login
     *
     * @param lastLogin the value for t_user.last_login
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.created_time
     *
     * @return the value of t_user.created_time
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.created_time
     *
     * @param createdTime the value for t_user.created_time
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.updated_time
     *
     * @return the value of t_user.updated_time
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.updated_time
     *
     * @param updatedTime the value for t_user.updated_time
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}