package com.cluser.dao.model;

import java.util.Date;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.full_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.display_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password_meta_info
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String passwordMetaInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password_status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String passwordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.salt
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email_verify_status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String emailVerifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.telephone
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mobile
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mobile_verify_status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String mobileVerifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.gender
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.type
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.avatar
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.created_by
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_login
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.created_time
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.updated_time
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.full_name
     *
     * @return the value of t_user.full_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.full_name
     *
     * @param fullName the value for t_user.full_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.display_name
     *
     * @return the value of t_user.display_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.display_name
     *
     * @param displayName the value for t_user.display_name
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password_meta_info
     *
     * @return the value of t_user.password_meta_info
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getPasswordMetaInfo() {
        return passwordMetaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password_meta_info
     *
     * @param passwordMetaInfo the value for t_user.password_meta_info
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setPasswordMetaInfo(String passwordMetaInfo) {
        this.passwordMetaInfo = passwordMetaInfo == null ? null : passwordMetaInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password_status
     *
     * @return the value of t_user.password_status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getPasswordStatus() {
        return passwordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password_status
     *
     * @param passwordStatus the value for t_user.password_status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setPasswordStatus(String passwordStatus) {
        this.passwordStatus = passwordStatus == null ? null : passwordStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.salt
     *
     * @return the value of t_user.salt
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.salt
     *
     * @param salt the value for t_user.salt
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email_verify_status
     *
     * @return the value of t_user.email_verify_status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getEmailVerifyStatus() {
        return emailVerifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email_verify_status
     *
     * @param emailVerifyStatus the value for t_user.email_verify_status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setEmailVerifyStatus(String emailVerifyStatus) {
        this.emailVerifyStatus = emailVerifyStatus == null ? null : emailVerifyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.telephone
     *
     * @return the value of t_user.telephone
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.telephone
     *
     * @param telephone the value for t_user.telephone
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mobile
     *
     * @return the value of t_user.mobile
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mobile
     *
     * @param mobile the value for t_user.mobile
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mobile_verify_status
     *
     * @return the value of t_user.mobile_verify_status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getMobileVerifyStatus() {
        return mobileVerifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mobile_verify_status
     *
     * @param mobileVerifyStatus the value for t_user.mobile_verify_status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setMobileVerifyStatus(String mobileVerifyStatus) {
        this.mobileVerifyStatus = mobileVerifyStatus == null ? null : mobileVerifyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.gender
     *
     * @return the value of t_user.gender
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.gender
     *
     * @param gender the value for t_user.gender
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.type
     *
     * @return the value of t_user.type
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.type
     *
     * @param type the value for t_user.type
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.avatar
     *
     * @return the value of t_user.avatar
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.avatar
     *
     * @param avatar the value for t_user.avatar
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.created_by
     *
     * @return the value of t_user.created_by
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.created_by
     *
     * @param createdBy the value for t_user.created_by
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_login
     *
     * @return the value of t_user.last_login
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_login
     *
     * @param lastLogin the value for t_user.last_login
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.created_time
     *
     * @return the value of t_user.created_time
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.created_time
     *
     * @param createdTime the value for t_user.created_time
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.updated_time
     *
     * @return the value of t_user.updated_time
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.updated_time
     *
     * @param updatedTime the value for t_user.updated_time
     *
     * @mbggenerated Fri Dec 09 21:21:27 CST 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}