package com.cluser.dao.model;

public class TUserOrgKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_org.user_id
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_org.org_id
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    private Long orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_org.user_id
     *
     * @return the value of t_user_org.user_id
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_org.user_id
     *
     * @param userId the value for t_user_org.user_id
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_org.org_id
     *
     * @return the value of t_user_org.org_id
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_org.org_id
     *
     * @param orgId the value for t_user_org.org_id
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }
}