package com.cluser.dao.mapper;

import com.cluser.dao.model.TOrganization;
import com.cluser.dao.model.TOrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int countByExample(TOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int deleteByExample(TOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    @Delete({
        "delete from t_organization",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    @Insert({
        "insert into t_organization (name, description, ",
        "address, email, ",
        "type, status, more_info, ",
        "created_time, updated_time)",
        "values (#{name,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{moreInfo,jdbcType=VARCHAR}, ",
        "#{createdTime,jdbcType=TIMESTAMP}, #{updatedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int insertSelective(TOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    List<TOrganization> selectByExample(TOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    @Select({
        "select",
        "id, name, description, address, email, type, status, more_info, created_time, ",
        "updated_time",
        "from t_organization",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TOrganization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") TOrganization record, @Param("example") TOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int updateByExample(@Param("record") TOrganization record, @Param("example") TOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int updateByPrimaryKeySelective(TOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    @Update({
        "update t_organization",
        "set name = #{name,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "more_info = #{moreInfo,jdbcType=VARCHAR},",
          "created_time = #{createdTime,jdbcType=TIMESTAMP},",
          "updated_time = #{updatedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TOrganization record);
}