package com.cluser.dao.mapper;

import com.cluser.dao.model.TUserOrgExample;
import com.cluser.dao.model.TUserOrgKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface TUserOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_org
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int countByExample(TUserOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_org
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int deleteByExample(TUserOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_org
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    @Delete({
        "delete from t_user_org",
        "where user_id = #{userId,jdbcType=BIGINT}",
          "and org_id = #{orgId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(TUserOrgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_org
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    @Insert({
        "insert into t_user_org (user_id, org_id)",
        "values (#{userId,jdbcType=BIGINT}, #{orgId,jdbcType=BIGINT})"
    })
    int insert(TUserOrgKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_org
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int insertSelective(TUserOrgKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_org
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    List<TUserOrgKey> selectByExample(TUserOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_org
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") TUserOrgKey record, @Param("example") TUserOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_org
     *
     * @mbggenerated Mon Dec 12 09:41:52 CST 2016
     */
    int updateByExample(@Param("record") TUserOrgKey record, @Param("example") TUserOrgExample example);
}