package com.cluser.dao.mapper;

import com.cluser.dao.model.TUser;
import com.cluser.dao.model.TUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    int countByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    int deleteByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    @Delete({
        "delete from t_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    @Insert({
        "insert into t_user (username, full_name, ",
        "preferred_username, nickname, ",
        "birthdate, password_meta_info, ",
        "password, password_status, ",
        "gender, picture, ",
        "website, salt, email, ",
        "email_verified, phone_number, ",
        "phone_number_verified, zoneinfo, ",
        "profile, locale, ",
        "type, status, address, ",
        "created_by, last_login, ",
        "created_time, updated_time)",
        "values (#{username,jdbcType=VARCHAR}, #{fullName,jdbcType=VARCHAR}, ",
        "#{preferredUsername,jdbcType=VARCHAR}, #{nickname,jdbcType=VARCHAR}, ",
        "#{birthdate,jdbcType=TIMESTAMP}, #{passwordMetaInfo,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{passwordStatus,jdbcType=VARCHAR}, ",
        "#{gender,jdbcType=VARCHAR}, #{picture,jdbcType=VARCHAR}, ",
        "#{website,jdbcType=VARCHAR}, #{salt,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{emailVerified,jdbcType=BIT}, #{phoneNumber,jdbcType=VARCHAR}, ",
        "#{phoneNumberVerified,jdbcType=BIT}, #{zoneinfo,jdbcType=VARCHAR}, ",
        "#{profile,jdbcType=VARCHAR}, #{locale,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{createdBy,jdbcType=BIGINT}, #{lastLogin,jdbcType=TIMESTAMP}, ",
        "#{createdTime,jdbcType=TIMESTAMP}, #{updatedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    int insertSelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    List<TUser> selectByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    @Select({
        "select",
        "id, username, full_name, preferred_username, nickname, birthdate, password_meta_info, ",
        "password, password_status, gender, picture, website, salt, email, email_verified, ",
        "phone_number, phone_number_verified, zoneinfo, profile, locale, type, status, ",
        "address, created_by, last_login, created_time, updated_time",
        "from t_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") TUser record, @Param("example") TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    int updateByExample(@Param("record") TUser record, @Param("example") TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    int updateByPrimaryKeySelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Dec 12 10:02:28 CST 2016
     */
    @Update({
        "update t_user",
        "set username = #{username,jdbcType=VARCHAR},",
          "full_name = #{fullName,jdbcType=VARCHAR},",
          "preferred_username = #{preferredUsername,jdbcType=VARCHAR},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "birthdate = #{birthdate,jdbcType=TIMESTAMP},",
          "password_meta_info = #{passwordMetaInfo,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "password_status = #{passwordStatus,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=VARCHAR},",
          "picture = #{picture,jdbcType=VARCHAR},",
          "website = #{website,jdbcType=VARCHAR},",
          "salt = #{salt,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "email_verified = #{emailVerified,jdbcType=BIT},",
          "phone_number = #{phoneNumber,jdbcType=VARCHAR},",
          "phone_number_verified = #{phoneNumberVerified,jdbcType=BIT},",
          "zoneinfo = #{zoneinfo,jdbcType=VARCHAR},",
          "profile = #{profile,jdbcType=VARCHAR},",
          "locale = #{locale,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "created_by = #{createdBy,jdbcType=BIGINT},",
          "last_login = #{lastLogin,jdbcType=TIMESTAMP},",
          "created_time = #{createdTime,jdbcType=TIMESTAMP},",
          "updated_time = #{updatedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TUser record);
}